name: Profile Metrics

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - assets/metrics-*.svg
  schedule:
    - cron: "0 17 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Full-year isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: zzl-hyun
          base: ""
          config_timezone: Asia/Seoul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Languages activity
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: zzl-hyun
          base: ""
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: >-
            joomidang/paper-summarizer-backend,
            joomidang/paper-summarizer-summry-worker,
            UMC-GameCast/gamecast-server@dev,
            project-GMG/backend
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 8
          plugin_languages_threshold: 1%
          plugin_languages_analysis_timeout: 30
          commits_authoring: >-
            zzl-hyun,
            kimgihyun877@gmail.com,
            74497151+zzl-hyun@users.noreply.github.com
